/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  FileSystemApi,
  InstanceApi,
  InstanceTypeApi,
  KeyApi,
  SSHKeyApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { LambdaCustom } from "./client-custom";

export class Lambda extends LambdaCustom {
  readonly fileSystem: FileSystemApi;
  readonly instance: InstanceApi;
  readonly instanceType: InstanceTypeApi;
  readonly key: KeyApi;
  readonly sSHKey: SSHKeyApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.fileSystem = new FileSystemApi(configuration);
    this.instance = new InstanceApi(configuration);
    this.instanceType = new InstanceTypeApi(configuration);
    this.key = new KeyApi(configuration);
    this.sSHKey = new SSHKeyApi(configuration);
  }

}
