/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Unique identifier for the type of error
 * @export
 * @enum {string}
 */
export type ErrorCode = 'global/unknown' | 'global/invalid-api-key' | 'global/account-inactive' | 'global/invalid-address' | 'global/invalid-parameters' | 'global/object-does-not-exist' | 'global/quota-exceeded' | 'instance-operations/launch/insufficient-capacity' | 'instance-operations/launch/file-system-in-wrong-region' | 'instance-operations/launch/file-systems-not-supported' | 'ssh-keys/key-in-use'

