/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelError } from './model-error';

/**
 * 
 * @export
 * @interface ErrorResponseBody
 */
export interface ErrorResponseBody {
    /**
     * 
     * @type {ModelError}
     * @memberof ErrorResponseBody
     */
    'error': ModelError;
    /**
     * Details about errors on a per-parameter basis
     * @type {{ [key: string]: ModelError; }}
     * @memberof ErrorResponseBody
     */
    'field_errors'?: { [key: string]: ModelError; };
}

