/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Instance } from './instance';

/**
 * 
 * @export
 * @interface InstanceTerminateInstanceResponseData
 */
export interface InstanceTerminateInstanceResponseData {
    /**
     * List of instances that were terminated. Note: this list might not contain all instances requested to be terminated.
     * @type {Array<Instance>}
     * @memberof InstanceTerminateInstanceResponseData
     */
    'terminated_instances': Array<Instance>;
}

