/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Instance } from './instance';

/**
 * 
 * @export
 * @interface InstanceRestartInstancesResponseData
 */
export interface InstanceRestartInstancesResponseData {
    /**
     * List of instances that were restarted. Note: this list might not contain all instances requested to be restarted.
     * @type {Array<Instance>}
     * @memberof InstanceRestartInstancesResponseData
     */
    'restarted_instances': Array<Instance>;
}

