/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InstanceTypeGetListResponseDataValue } from './instance-type-get-list-response-data-value';

/**
 * 
 * @export
 * @interface InstanceTypeGetListResponse
 */
export interface InstanceTypeGetListResponse {
    /**
     * Dict of instance_type_name to instance_type and region availability.
     * @type {{ [key: string]: InstanceTypeGetListResponseDataValue; }}
     * @memberof InstanceTypeGetListResponse
     */
    'data': { [key: string]: InstanceTypeGetListResponseDataValue; };
}

