/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InstanceRestartInstancesRequest
 */
export interface InstanceRestartInstancesRequest {
    /**
     * The unique identifiers (IDs) of the instances to restart
     * @type {Array<string>}
     * @memberof InstanceRestartInstancesRequest
     */
    'instance_ids': Array<string>;
}

