/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InstanceTypeSpecs
 */
export interface InstanceTypeSpecs {
    /**
     * Number of virtual CPUs
     * @type {number}
     * @memberof InstanceTypeSpecs
     */
    'vcpus': number;
    /**
     * Amount of RAM, in gibibytes (GiB)
     * @type {number}
     * @memberof InstanceTypeSpecs
     */
    'memory_gib': number;
    /**
     * Amount of storage, in gibibytes (GiB).
     * @type {number}
     * @memberof InstanceTypeSpecs
     */
    'storage_gib': number;
}

