/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InstanceCreateInstancesResponseData
 */
export interface InstanceCreateInstancesResponseData {
    /**
     * The unique identifiers (IDs) of the launched instances. Note: if a quantity was specified, fewer than the requested quantity might have been launched.
     * @type {Array<string>}
     * @memberof InstanceCreateInstancesResponseData
     */
    'instance_ids': Array<string>;
}

