/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InstanceTerminateInstanceRequest
 */
export interface InstanceTerminateInstanceRequest {
    /**
     * The unique identifiers (IDs) of the instances to terminate
     * @type {Array<string>}
     * @memberof InstanceTerminateInstanceRequest
     */
    'instance_ids': Array<string>;
}

