/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InstanceTypeSpecs } from './instance-type-specs';

/**
 * Hardware configuration and pricing of an instance type
 * @export
 * @interface InstanceType
 */
export interface InstanceType {
    /**
     * Long name of the instance type
     * @type {string}
     * @memberof InstanceType
     */
    'description': string;
    /**
     * Name of an instance type
     * @type {string}
     * @memberof InstanceType
     */
    'name': string;
    /**
     * Price of the instance type, in US cents per hour
     * @type {number}
     * @memberof InstanceType
     */
    'price_cents_per_hour': number;
    /**
     * 
     * @type {InstanceTypeSpecs}
     * @memberof InstanceType
     */
    'specs': InstanceTypeSpecs;
}

