/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InstanceCreateInstancesRequest
 */
export interface InstanceCreateInstancesRequest {
    /**
     * Short name of a region
     * @type {string}
     * @memberof InstanceCreateInstancesRequest
     */
    'region_name': string;
    /**
     * Name of an instance type
     * @type {string}
     * @memberof InstanceCreateInstancesRequest
     */
    'instance_type_name': string;
    /**
     * Names of the SSH keys to allow access to the instances. Currently, exactly one SSH key must be specified.
     * @type {Array<string>}
     * @memberof InstanceCreateInstancesRequest
     */
    'ssh_key_names': Array<string>;
    /**
     * Names of the file systems to attach to the instances. Currently, only one (if any) file system may be specified.
     * @type {Array<string>}
     * @memberof InstanceCreateInstancesRequest
     */
    'file_system_names'?: Array<string>;
    /**
     * Number of instances to launch
     * @type {number}
     * @memberof InstanceCreateInstancesRequest
     */
    'quantity'?: number;
    /**
     * User-provided name for the instance
     * @type {string}
     * @memberof InstanceCreateInstancesRequest
     */
    'name'?: string | null;
}

