/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Instance } from './instance';

/**
 * 
 * @export
 * @interface InstanceGetDetailsResponse
 */
export interface InstanceGetDetailsResponse {
    /**
     * 
     * @type {Instance}
     * @memberof InstanceGetDetailsResponse
     */
    'data': Instance;
}

