/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SshKey } from './ssh-key';

/**
 * The added or generated SSH public key. If a new key pair was generated, the response body contains a `private_key` property that *must* be saved locally. Lambda Cloud does not store private keys.
 * @export
 * @interface KeyAddSshKeyResponse
 */
export interface KeyAddSshKeyResponse {
    /**
     * 
     * @type {SshKey}
     * @memberof KeyAddSshKeyResponse
     */
    'data': SshKey;
}

