/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SshKey } from './ssh-key';

/**
 * 
 * @export
 * @interface KeyGetListResponse
 */
export interface KeyGetListResponse {
    /**
     * 
     * @type {Array<SshKey>}
     * @memberof KeyGetListResponse
     */
    'data': Array<SshKey>;
}

