/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The name for the SSH key. Optionally, an existing public key can be supplied for the `public_key` property. If the `public_key` property is omitted, a new key pair is generated. The private key is returned in the response.
 * @export
 * @interface KeyAddSshKeyRequest
 */
export interface KeyAddSshKeyRequest {
    /**
     * Name of the SSH key
     * @type {string}
     * @memberof KeyAddSshKeyRequest
     */
    'name': string;
    /**
     * Public key for the SSH key
     * @type {string}
     * @memberof KeyAddSshKeyRequest
     */
    'public_key'?: string;
}

