/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorCode } from './error-code';

/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * Unique identifier for the type of error
     * @type {ErrorCode}
     * @memberof ModelError
     */
    'code': ErrorCode;
    /**
     * Detailed description of the error
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
    /**
     * Suggestion of possible ways to fix the error.
     * @type {string}
     * @memberof ModelError
     */
    'suggestion'?: string | null;
}

