/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * Long name of a region
     * @type {string}
     * @memberof Region
     */
    'description': string;
    /**
     * Short name of a region
     * @type {string}
     * @memberof Region
     */
    'name': string;
}

