/*
Lambda Cloud API

API for interacting with the Lambda GPU Cloud

The version of the OpenAPI document: 1.5.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about a stored SSH key, which can be used to access instances over SSH
 * @export
 * @interface SshKey
 */
export interface SshKey {
    /**
     * Unique identifier (ID) of an SSH key
     * @type {string}
     * @memberof SshKey
     */
    'id': string;
    /**
     * Name of the SSH key
     * @type {string}
     * @memberof SshKey
     */
    'name': string;
    /**
     * Public key for the SSH key
     * @type {string}
     * @memberof SshKey
     */
    'public_key': string;
    /**
     * Private key for the SSH key. Only returned when generating a new key pair.
     * @type {string}
     * @memberof SshKey
     */
    'private_key'?: string | null;
}

